version: '3'

services:
  back:
    container_name: frontflow_back
    ports:
      - 1337:1337
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/back
    
  front:
    container_name: frontflow_front
    ports: 
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt